2025-04-27 17:36:10,851-INFO-Data Processing Initialized...
2025-04-27 17:40:24,157-INFO-Data Processing Initialized...
2025-04-27 17:40:24,596-INFO-Data loaded sucessfully
2025-04-27 17:40:24,692-ERROR-Error while encoding Target DataFrame.dropna() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
2025-04-27 17:41:48,082-INFO-Data Processing Initialized...
2025-04-27 17:41:48,367-INFO-Data loaded sucessfully
2025-04-27 17:41:48,463-ERROR-Error while encoding Target DataFrame.dropna() takes 1 positional argument but 2 were given
2025-04-27 17:42:09,247-INFO-Data Processing Initialized...
2025-04-27 17:42:09,522-INFO-Data loaded sucessfully
2025-04-27 17:42:09,618-ERROR-Error while encoding Target DataFrame.dropna() takes 1 positional argument but 2 were given
2025-04-27 17:42:56,263-INFO-Data Processing Initialized...
2025-04-27 17:42:56,534-INFO-Data loaded sucessfully
2025-04-27 17:42:56,629-ERROR-Error while encoding Target DataFrame.dropna() takes 1 positional argument but 2 were given
2025-04-27 17:43:58,373-INFO-Data Processing Initialized...
2025-04-27 17:43:58,647-INFO-Data loaded sucessfully
2025-04-27 17:43:58,742-ERROR-Error while encoding Target DataFrame.dropna() takes 1 positional argument but 2 were given
2025-04-27 17:45:03,627-INFO-Data Processing Initialized...
2025-04-27 17:45:03,923-INFO-Data loaded sucessfully
2025-04-27 17:45:04,045-ERROR-Error while encoding Target LabelEncoder.fit_transform() missing 1 required positional argument: 'y'
2025-04-27 17:46:17,087-INFO-Data Processing Initialized...
2025-04-27 17:46:17,378-INFO-Data loaded sucessfully
2025-04-27 17:46:17,517-INFO-Target Variable Encoded...
2025-04-27 17:46:17,526-ERROR-Error while splitting Data'DataFrame' object is not callable
2025-04-27 17:47:22,433-INFO-Data Processing Initialized...
2025-04-27 17:47:22,754-INFO-Data loaded sucessfully
2025-04-27 17:47:22,894-INFO-Target Variable Encoded...
2025-04-27 17:47:23,024-INFO-Splitted and saved sucessfully...
2025-04-27 17:47:23,033-INFO-Data Processing Completed...
2025-04-27 18:30:40,696-INFO-Model Training Initailized...
2025-04-27 18:30:41,076-INFO-Processed Data loaded sucessfully...
2025-04-27 18:30:41,076-ERROR-Error while create feature pipeline'ModelTraining' object has no attribute 'categoical'
2025-04-27 18:31:06,746-INFO-Model Training Initailized...
2025-04-27 18:31:06,794-INFO-Processed Data loaded sucessfully...
2025-04-27 18:31:06,794-ERROR-Error while create feature pipeline'ModelTraining' object has no attribute 'categorical'
2025-04-27 23:55:46,455-INFO-Model Training Initailized...
2025-04-27 23:55:46,526-INFO-Processed Data loaded sucessfully...
2025-04-27 23:55:46,526-ERROR-Error while create feature pipelinelist.remove(x): x not in list
2025-04-27 23:57:10,214-INFO-Model Training Initailized...
2025-04-27 23:57:10,254-INFO-Processed Data loaded sucessfully...
2025-04-27 23:57:10,254-INFO-Feature Engineering Pipeline Created...
2025-04-27 23:57:10,376-ERROR-Error while Training Model 'numpy.ndarray' object has no attribute 'fit'
2025-04-27 23:59:12,038-INFO-Model Training Initailized...
2025-04-27 23:59:12,078-INFO-Processed Data loaded sucessfully...
2025-04-27 23:59:12,078-INFO-Feature Engineering Pipeline Created...
2025-04-27 23:59:13,174-INFO-Training and saving of model done...
2025-04-27 23:59:13,175-ERROR-Error while evaluating model 'Pipeline' object is not callable
